# Puerto (usa el asignado por Azure o 8080 por defecto)
server.port=${PORT:8080}

# Configuración de conexión a la base de datos Azure SQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://f4u-database.database.windows.net:1433;database=f4u-database;encrypt=true;trustServerCertificate=false;loginTimeout=30;}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:CloudSA85393efd}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:F4U_2025.}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Monitorización básica
management.endpoints.web.exposure.include=health,info

# Desactivar H2 en despliegue
spring.h2.console.enabled=false
